<#
.SYNOPSIS
Generates sample GetComputerHealth HTML reports without running the full collection pipeline.

.DESCRIPTION
Creates synthetic findings and renders:
- a non-interactive/email-safe HTML body
- an interactive HTML report

Both files are written under a timestamped folder in .\temp unless -OutputDir is supplied.

.EXAMPLE
.\scripts\diagnostics\New-SampleHealthReport.ps1

.EXAMPLE
.\scripts\diagnostics\New-SampleHealthReport.ps1 -CountPerLevel 3
#>
[CmdletBinding()]
param(
  [ValidateRange(1, 9)]
  [int]$CountPerLevel = 2,

  [string]$OutputDir
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..\..')
$reportingPath = Join-Path $repoRoot 'reporting.ps1'
. $reportingPath

if ([string]::IsNullOrWhiteSpace($OutputDir)) {
  $timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
  $OutputDir = Join-Path $repoRoot ("temp\sample-report-{0}" -f $timestamp)
}

New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

$messages = New-Object System.Collections.ArrayList
$levels = @('failure', 'warning', 'notice')
$counter = 0

foreach ($level in $levels) {
  for ($i = 1; $i -le $CountPerLevel; $i++) {
    $counter++
    $hash = '{0:x8}' -f $counter
    $comment = "This is sample comment $i for level $level.`nSecond line for layout testing.`nThird line with extra detail."
    [void]$messages.Add([pscustomobject]@{
      Computer        = ('SRV{0}' -f $counter)
      Suppressed      = $false
      Level           = $level
      EffectiveLevel  = $level
      Message         = ('Sample {0} finding #{1}' -f $level, $i)
      Comment         = $comment
      Hash            = $hash
      Emitter         = 'New-SampleHealthReport'
      TimeUtc         = (Get-Date).ToUniversalTime().ToString('o')
      SuppressedUntil = ''
    })
  }
}

for ($i = 1; $i -le $CountPerLevel; $i++) {
  $counter++
  [void]$messages.Add([pscustomobject]@{
    Computer        = ('SRV{0}' -f $counter)
    Suppressed      = $true
    Level           = 'warning'
    EffectiveLevel  = 'postponed'
    Message         = ('Sample postponed warning #{0}' -f $i)
    Comment         = "This postponed finding remains visible in the interactive report."
    Hash            = ('{0:x8}' -f $counter)
    Emitter         = 'New-SampleHealthReport'
    TimeUtc         = (Get-Date).ToUniversalTime().ToString('o')
    SuppressedUntil = (Get-Date).AddDays(14).ToString('yyyy-MM-dd')
  })
}

$reportRows = @(Convert-HealthMessagesToReportRows -Messages $messages)
$interactiveRows = @(Convert-HealthReportRowsToInteractiveRows -Rows $reportRows)
$emailSignature = [pscustomobject]@{
  Text = ''
  Html = ''
  HtmlTop = 'Sample report generated by New-SampleHealthReport.ps1'
  HtmlBottom = 'Synthetic findings for layout testing'
}

$htmlParts = @()
$htmlSynopsis = Convert-HealthSynopsisToHtml -Messages $reportRows
if (-not [string]::IsNullOrWhiteSpace($htmlSynopsis)) {
  $htmlParts += $htmlSynopsis
}
$htmlParts += Convert-HealthMessagesToHtmlTable -Messages $reportRows
$emailBodyHtml = Add-HealthEmailSignature -Body ($htmlParts -join '') -BodyAsHtml -Signature $emailSignature
$interactiveHtml = Get-HealthInteractiveHtmlReport -Rows $interactiveRows -Title 'Sample Health Report' -FooterHtml $emailSignature.HtmlBottom

$emailPath = Join-Path $OutputDir 'sample-email-report.html'
$interactivePath = Join-Path $OutputDir 'sample-interactive-report.html'
Save-HealthHtmlReport -Path $emailPath -Html $emailBodyHtml
Save-HealthHtmlReport -Path $interactivePath -Html $interactiveHtml

Write-Host ("Wrote sample email HTML: {0}" -f $emailPath)
Write-Host ("Wrote sample interactive HTML: {0}" -f $interactivePath)
